version: '3.9'

networks:
  kpl:
  falcon:
    driver: bridge
services:
  web:
    build: ./web/
    image: kpl_web
    volumes:
      - ./web/:/app/
    ports:
      - 5555:5555
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kpl_api
    volumes:
      - ./kpl/:/kpl/kpl
      - ./web/dist/:/app/dist/
      - ./web/static/:/app/static/
    networks:
      - kpl
      - falcon
    depends_on:
      - "crossbar"
    ports:
      - 8888:80
    env_file:
      - .address
  crossbar:
    image: crossbario/crossbar
    volumes:
      - ./.crossbar/:/.crossbar/
    ports:
      - 8080:8080